import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "@/app/globals.scss";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AuthProvider } from "@/context/AuthContext";

const roboto = Roboto({
    weight: "400",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <AuthProvider>
                    <AntdRegistry>{children}</AntdRegistry>
                </AuthProvider>
            </body>
        </html>
    );
}
